#!/bin/bash

echo ""
echo "Deployment..."
echo "----------------------------------------------"
MY_IP=`ifconfig br0 | grep -w inet | awk '{print $2}'`
ip_1=`echo ${MY_IP} | awk -F. '{print $1}'`
ip_2=`echo ${MY_IP} | awk -F. '{print $2}'`
ip_3=`echo ${MY_IP} | awk -F. '{print $3}'`
name=`cat /home/server.xml | grep -i '<name>' | awk -F\> '{print $2}' | awk -F\< '{print $1}'`
mac=`cat /home/server.xml | grep -i 'mac address' | sed "s/'//g" | awk -F= '{print $2}' | awk -F/ '{print $1}'`
mac_1=`cat /home/server.xml | grep -i 'mac address' | sed "s/'//g" | awk -F= '{print $2}' | awk -F/ '{print $1}' | awk -F: '{print $1}'`
mac_2=`cat /home/server.xml | grep -i 'mac address' | sed "s/'//g" | awk -F= '{print $2}' | awk -F/ '{print $1}' | awk -F: '{print $2}'`
mac_3=`cat /home/server.xml | grep -i 'mac address' | sed "s/'//g" | awk -F= '{print $2}' | awk -F/ '{print $1}' | awk -F: '{print $3}'`
mac_4=`cat /home/server.xml | grep -i 'mac address' | sed "s/'//g" | awk -F= '{print $2}' | awk -F/ '{print $1}' | awk -F: '{print $4}'`
uuid=`cat /home/server.xml | grep -i uuid | awk -F\> '{print $2}' | awk -F\< '{print $1}'`
source_xml_file=`cat /home/server.xml | grep -i 'source file' | awk -F= '{print $2}' | awk -F\' '{print $2}' | awk 'NR==1{print $0}'`
cat > /home/ifcfg-eth0_init << EOF
TYPE=Ethernet
BOOTPROTO=static
NAME=eth0
DEVICE=eth0
ONBOOT=yes
IPADDR=x.x.x.x
PREFIX=24
EOF
for i in `seq -w ${NUM_START} ${NUM_END}`
do
	xml_file=server-${i}.xml
	dir=server-${i}
	qcow2_disk=server-${i}.qcow2
	mkdir -p /home/Date/server/${dir}
	cp /home/server.xml /home/Date/server/${dir}/${xml_file}
	cp /home/server.qcow2 /home/Date/server/${dir}/${qcow2_disk}
	cp /home/ifcfg-eth0_init /home/ifcfg-eth0
	sed -i "s,${name},server-${i},g" /home/Date/server/${dir}/${xml_file}
	uuid_new=`uuidgen`
	sed -i "s,${uuid},${uuid_new},g" /home/Date/server/${dir}/${xml_file}
	mac_new_1=`openssl rand -hex 1`
	mac_new_2=`openssl rand -hex 1`
	sed -i "s,${mac},${mac_1}:${mac_2}:${mac_3}:${mac_4}:${mac_new_1}:${mac_new_2},g" /home/Date/server/${dir}/${xml_file}
	sed -i "s,${source_xml_file},/home/Date/server/${dir}/${qcow2_disk},g" /home/Date/server/${dir}/${xml_file}
	sed -i "s,x.x.x.x,${ip_1}.${ip_2}.${ip_3}.1${i},g" /home/ifcfg-eth0
	virt-copy-in -a /home/Date/server/${dir}/${qcow2_disk} /home/ifcfg-eth0 /etc/sysconfig/network-scripts/
	virsh define /home/Date/server/${dir}/${xml_file} &> /dev/null
	virsh start server-${i}
	rm -rf /home/ifcfg-eth0 /home/ifcfg-eth0_init
done